name: Run Python script

on:
  push:
    branches:
     -main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace with the Python version you need

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Replace with your dependency installation command
        
    - name: Set up OpenAI API key
      run: 
       echo "export OPENAI_API_KEY=$OPENAI_API_KEY" >> $GITHUB_ENV
       echo "export SERPAPI_API_KEY=$SERPAPI_API_KEY" >> $GITHUB_ENV
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI }}
        SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
    - name: Execute Python script
           
      run: python stanalysis.py
   

    
